# Generated by Django 3.1 on 2021-07-17 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210716_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='password',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='username',
        ),
    ]
